Adds Object Detection Algorithm
awslabs/mlspace pull request #23
Opened 2024-03-27 23:37 UTC by LightSeekerSC

*Issue #, if available:* https://issues.amazon.com/issues/AIML-ADC-7256

*Description of changes:* Adds the Object Detection algorithm for use in training and HPO jobs

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-03-28 12:16 UTC, KyleLilly requested changes

2024-03-28 12:16 UTC, KyleLilly commented on frontend/src/entities/jobs/algorithms.tsx
> +        // Docs: https://docs.aws.amazon.com/sagemaker/latest/dg/linear-learner.html
Wrong doc link.

2024-03-28 12:16 UTC, KyleLilly commented on frontend/src/entities/jobs/algorithms.tsx
> +            key: 'crop_size',
```suggestion
            key: 'base_network',
```

2024-03-28 20:24 UTC, KyleLilly approved these changes

2024-03-29 01:50 UTC, dustins submitted a review, later dismissed

2024-03-29 15:07 UTC, LightSeekerSC commented
Fixed the backend tests that were failing. All else is the same

2024-04-01 11:51 UTC, dustins approved these changes

2024-04-01 14:43 UTC, KyleLilly approved these changes

2024-04-01 17:04 UTC, merged